screenshot:
  description: Screenshot and draw
  script: |
    file="$(mktemp -t screenshot_$(date +'%Y%m%d_%H%M%S').XXXXXXX)"
    niri msg action screenshot --path $file
    swappy -f $file
  icon: "draw-arrow"

bluetooth:
  description: Connect to Airpods
  binary: btw
  icon: "draw-star"
